CrankyJanes/CrankyJanes.WebUI/Controllers/ListingsController.cs
using CrankyJanes.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrankyJanes.WebUI.Controllers
{
    [Authorize(Roles = UserRoles.StandardUser)]
    public class ListingsController : Controller
    {
        //
        // GET: /Listings/

        [HttpGet]
        public ActionResult SearchResults()
        {
            return View();
        }

        public ActionResult Index()
        {
            ViewBag.Message = "Your listing page.";
            return View();
        }


        [HttpGet]
        public ActionResult Create()
        {
            using (var context = CoreData.Context)
            {
                var categories = new List<Category>
                {
                    new Category {CategoryName = "Select a Category", ID = -1}
                };

                categories.AddRange(context.FilteredCategories.OrderBy(c => c.CategoryName).ToList());
                ViewBag.categories = categories;

                return View(new Listing() { ListingProperties = new List<ListingProperty>() });
            }
        }

        [HttpPost]
        public ActionResult UpdateProperties(int id)
        {
            Listing listing = null;
            if (id > -1)
            {
                listing = new Listing() { ListingProperties = new List<ListingProperty>(), CategoryID = id };
                using (var context = CoreData.Context)
                {
                    var category = context.Categories
                        .Include("PropertySpecifications")
                        .Include("PropertySpecifications.ValidationRule")
                        .Include("ParentCategory")
                        .Include("ParentCategory.PropertySpecifications")
                        .Include("ParentCategory.PropertySpecifications.ValidationRule")
                        .SingleOrDefault(c => c.ID == listing.CategoryID);

                    var dollars = context.ValidationRules.Where(x => x.Name == "Dollars");

                    var categoryHeirarchy = new Stack<Category>();
                    listing.Category = category;
                    do
                    {
                        categoryHeirarchy.Push(category);
                        category = category.ParentCategory;
                    } while (category != null);

                    while (categoryHeirarchy.Any())
                    {
                        category = categoryHeirarchy.Pop();
                        foreach (var spec in category.PropertySpecifications)
                        {
                            var prop = spec.ToProperty();
                            listing.ListingProperties.Add(prop);
                        }
                    }
                }
            }

            return PartialView("_PropertyFields", listing);

            //return Json(listing);
        }

        [HttpPost]
        public ActionResult Create(Listing listing)
        {
            if (ModelState.IsValid && listing.ListingProperties.All(x => x.IsValid()))
            {
                using (var context = CoreData.Context)
                {
                    listing.Category = context.Categories.SingleOrDefault(c => c.ID == listing.CategoryID);
                    listing.Owner = this.GetUser(context);
                    listing.Owner.Listings.Add(listing);
                    context.SaveChanges();
                    return RedirectToAction("ViewDetails", listing.ID);
                }
            }
            else
            {
                return View(listing);
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult ViewDetails(long id = -1)
        {
            using (var context = CoreData.Context)
            {
                var listing = context.Listings.SingleOrDefault(l => l.ID == id);
                return View(listing);
            }
        }

        [HttpGet]
        public ActionResult MyListings()
        {
            using (var context = CoreData.Context)
            {
                var user = this.GetUser(context);
                var listings = context.Listings
                    .Include("ListingProperties")
                    .Where(l => l.Owner.UserName == user.UserName).ToArray();
                return View(listings);
            }
        }
    }
}

CrankyJanes/CrankyJanes.WebUI/Views/Listings/MyListings.cshtml
@model IEnumerable<CrankyJanes.Core.Listing>

@{
    ViewBag.Title = "MyListings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MyListings</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@foreach (var item in Model)
{
    <a href="/Listings/ViewDetails/@item.ID">
        @Html.Raw(item.ListingProperties.FirstOrDefault(p => p.PropertyName == "Description").PropertyValue);
    </a>
    <br />
}

CrankyJanes/CrankyJanes.WebUI/Views/Listings/SearchResults.cshtml
<script type="text/javascript">
    mixpanel.track('Search Results Page Load');
</script>

@{
    ViewBag.Title = "Cranky Jane's";
}
@section featured {
    
    <div class="listing_picture"></div><div class="listing_content">akdsjfadsf</div>


}

CrankyJanes/CrankyJanes.WebUI/Views/Listings/ViewDetails.cshtml
@model CrankyJanes.Core.Listing

@{
    ViewBag.Title = "ViewDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="mainSection2">
    <div id="search">
        <span id="searchPrompt">Search</span>
        <input id="searchInput" type="text" />
        <input id="searchButton" type="button" value=" " onclick='window.location="@Url.Action("SearchResults", "Home")    ";' />
    </div>
</div>

<div id="listingSection">
    <div id="listing">
        <div id="leftSection">
            <div id="listingHeader" style="font-size:30px;"><img src="/images/divider2.png" style="float:left;margin-top:15px;margin-left:38px;"> Biology <img src="/images/divider2.png" style="margin-top:15px;float:right;margin-right:38px;"></div>

            <div class="listing_content_detail">
                <img src="~/Images/bookbio.png" style="float:left;border-right:0px solid #808080;margin-right:5px;">
                <div id="productDesc">

                    <img src="~/Images/person.png" style="float:left;padding:10px;">
                    <h1>Sarah Mckinley</h1>
                    <h2>Biology Major</h2>
                    <img src="~/Images/horizdivider.png" style="margin-left:15px;">

                    <img src="~/Images/schoolico.png" style="float:left;padding:10px;">
                    <h1>College</h1>
                    <h2>Utah Valley University</h2>
                    <img src="~/Images/horizdivider.png" style="margin-left:15px;">

                    <img src="~/Images/person.png" style="float:left;padding:10px;">
                    <h1>Reputation</h1>
                    <h2>Feedback 6+ 1-</h2>
                    <img src="~/Images/horizdivider.png" style="margin-left:15px;">

                    <img src="~/Images/book.png" style="float:left;padding:10px;">
                    <h1>Condition</h1>
                    <h2>New - with access code</h2>
                    <img src="~/Images/horizdivider.png" style="margin-left:15px;">

                    <img src="~/Images/money.png" style="float:left;padding:10px;">
                    <h1>Price</h1>
                    <h2>$30</h2>

                </div>
            </div>
            <div class="aboutText" style="text-align:justify;padding:15px;margin-right:15px;">Here is the product description. This will cover the version of the book, the general contents, and the overall condition in more detail. Here is the product description. This will cover the version of the book, the general contents, and the overall condition in more detail. Here is the product description. This will cover the version of the book, the general contents, and the overall condition in more detail.</div>

            <div class="listingTitle" style="text-align:center;"><img src="/images/divider2.png" style="float:left;margin-top:10px;margin-left:38px;"> Seller <img src="/images/divider2.png" style="float:right;margin-top:10px;margin-right:38px;"></div>

            <div class="aboutText" style="text-align:justify;font-size:12px;margin-right:15px;">
                <img src="~/Images/student.png" style="float:left;margin-left:15px;margin-right:15px;border:10px solid #ffffff;">
                <div class="listingTitle" style="margin-top:20px;">
                    <font size="4px" color="#96b707">Student Name</font><br />
                    <font size="2px">University Name</font>
                </div>
                Description of student by the student or something. Description of student by the student or something. Description of student by the student or something. Description of student by the student or something. Description of student by the student or something.
            </div>

            <div class="clear"></div>

            <div class="listingTitle" style="text-align:center;"><img src="/images/divider2.png" style="float:left;margin-top:10px;margin-left:38px;"> Feedback <img src="/images/divider2.png" style="float:right;margin-top:10px;margin-right:38px;"></div>
            <img src="~/Images/feedback.png" style="align-content:center;padding:15px;">
        </div>
        <div id="rightSection" style="align-content:center;">
            <img src="~/Images/payment.png" style="padding-bottom:10px;padding-top:30px;">
            <img src="~/Images/getanaccount.png" style="padding-bottom:20px;padding-top:20px;">
            <img src="~/Images/amazon%20ad.png" />
        </div>
    </div>

</div>

CrankyJanes/CrankyJanes.WebUI/Views/Listings/_PropertyFields.cshtml
@model CrankyJanes.Core.Listing
@*<form method="post" id="listingPropertiesForm">
        <div id="listingPropertiesSection" data-bind="foreach: ListingProperties">
            <label class="propertyLabel"></label>
            <div>
                <input class="propertyField" data-bind="value: PropertyValue" />
            </div>
        </div>
        <input type="submit" data-bind="click: Save">Save</input>
    </form>*@

@if (Model != null)
{
    using (Html.BeginForm("Create", "Listings", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.CategoryID)
        @Html.EditorFor(m => m.ListingProperties)
        <input type="submit" value="Post Listing" />
    }
}

@Scripts.Render("~/bundles/knockout")

CrankyJanes/CrankyJanes.WebUI/Views/Listings/create.cshtml
@model CrankyJanes.Core.Listing
@using CrankyJanes.Core

@{
    ViewBag.Title = "NewItem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
<div class="editor-label">
    Category
</div>
<div class="editor-field">
    <select id="categoryDropDownList">
        @foreach (Category category in ViewBag.categories)
        {
            <option value="@category.ID">@category.CategoryName</option>
        }
    </select>
</div>

<div id="dynamicProperties">
    @Html.Partial("_PropertyFields")
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@*<input class="text-box single-line" id="ListingProperties_0__PropertyValue" name="ListingProperties[0].PropertyValue" type="text" value="">*@
@*<input id="ListingProperties_0__ValidationRuleName" name="ListingProperties[0].ValidationRuleName" type="hidden" value="Dollars">*@

@section Scripts {
    @Scripts.Render("~/bundles/knockout")
    <script type="text/javascript">
        $(function () {
            $('#categoryDropDownList').on('change', function (event) {
                $.ajax({
                    type: "POST",
                    url: "/Listings/UpdateProperties?id=" + $('#categoryDropDownList').val(),
                    success: function (html) {
                        $('#dynamicProperties').html(html);
                        var form = $('#dynamicProperties').find('form').first();

                        var ruleObj = { rules: {}, messages: {} };
                        var propDivs = $("div.listingProperty");
                        for (var i = 0; i < propDivs.length; ++i) {
                            var inputElementSelector = "input[name='ListingProperties[" + i + "].PropertyValue'";
                            var inputElement = $(inputElementSelector);
                            var ruleName = inputElement.attr("name");

                            var validationRule = $.parseJSON($(propDivs[i]).attr('data-validation-rule'));

                            var isApplicable = false;
                            var methodList = {};
                            if (validationRule != null && validationRule.Name != "Required") {
                                methodList.required = true;
                                isApplicable = true;
                                ruleObj.messages.required = validationRule.Message;
                            }
                            if (validationRule != null && validationRule.Name != "Required") {
                                methodList["regex"] = validationRule.ValidationRegex;
                                isApplicable = true;
                            }

                            if (isApplicable) {
                                ruleObj.rules[ruleName] = methodList;
                                ruleObj.messages[ruleName] = validationRule.Message;
                            }
                        }

                        form.validate(ruleObj);
                    }
                });
            });
        });
    </script>
}

CrankyJanes/CrankyJanes.WebUI/Views/Listings/index.cshtml
@{
    ViewBag.Title = "index";
}

<h2>index</h2>
@Html.Partial("listing")

CrankyJanes/CrankyJanes.WebUI/Views/Listings/listing.cshtml
<link href="~/Content/listings.css" rel="stylesheet" type="text/css" />
@for(int i = 0; i < 10; i++)
{
<div class="listing">
    <div class="listing_picture">&nbsp;</div>
    <div class="listing_content">
        <div class="listing_title">title</div>
        <div class="listing_description">description</div>
        <div class="listing_price">price</div>
        <div class="listing_contact">contact</div>
    </div>
    <div class="clear_float"></div>
</div>
}